FROM python:3.10

WORKDIR /myapp

COPY ./requirements.txt /myapp/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /myapp/requirements.txt

COPY ./ /myapp

CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8080"]